os: osx
language: objective-c
osx_image:
  - xcode11.4
  - xcode12
script:
  - set -o pipefail && xcodebuild test -project Sparkle.xcodeproj -scheme Distribution -derivedDataPath build -enableCodeCoverage YES | xcpretty
